- name: install nginx using playbook
  hosts: web
  become: true
  tasks:
  - name: install nginx using package
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      