- name: using playbook tags
  hosts: localhost
  become: yes
  tasks: 
  - name: using ping module
    ansible.builtin.ping:
  
  - name: using devops tags 
    ansible.builtin.debug:
      msg: "Hello Balaji, welcome to devops"
    tags:
    - devops

  - name: using aws tags 
    ansible.builtin.debug:
      msg: "Hello Balaji, welcome to devops with aws"
    tags:
    - devopsaws